name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=1.14.1
  - pip:
      - wandb==0.10.21
      - git+git@github.com:udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=project/solution/components
